### PR TITLE
Four enhancements

### PR DESCRIPTION
**Pull request by arifje**
- added a "generate" (bool) parameter to getVideoUrl(), just like getVideoThumbnailUrl(), to optionally skip encoding
- added return value false to getVideoThumbnailUrl() when ffmpeg is executed which prevents a URL is always returned, also in case of ffmpeg fails te run/create the thumbnail. This way we can do a check on the front end if we have a valid thumbnail URL.
- added new config parameter "createSubfolder" (boolean) to create the same subfolders that are defined in the upload target paths of the asset.
- added config option to prevent cache clearing

### CODE REVIEW

**Comment by khalwat** [comment]
Thanks for the PR! It looks like `:string` is designated as the return type, though... so it will error if we return a `bool` no?

**Comment by arifje** [comment]
getVideoUrl() does return a string and getVideoThumbnailUrl() can return false/null or  a string. The commit overview looks misleading, please check out the file.

I've tested it and it works!

**Comment by arifje** [comment]
Hi, would be great if you can check/approve my PR. Currently I am also working on a watermark feature. 

Cheers.

**Comment by arifje** [comment]
@khalwat any chance approving this PR? We've been testing with these changes and everything seems to work fine.

**Comment by khalwat** [comment]
I will do some testing to ensure nothing is broken from the changes in my test environments

**Comment by khalwat** [comment]
Thanks @skoften !

**Pull request merged**
